/* eslint-disable prefer-const */

import { choppers, divineSpot, foodCafe, pappiesMaestro, pizza, pizzaHut, shawarma as sharwarma, suyaBistro } from "@/assets/images";
import { food, groceries, restaurant } from "@/assets/svgs";
import { Product } from "@/lib/stores/CartStore";

export let discount = [
  {
    id: 1,
    title: "Sharwarma Plus+",
    image: sharwarma,
    rating: 4.7,
    deliveryFee: 200,
    deliveryTime: "20 min",
    discount: 40,
  },
  {
    id: 2,
    title: "Sharwarma Plus+",
    image: sharwarma,
    rating: 4.7,
    deliveryFee: 0,
    deliveryTime: "20 min",
    discount: 40,
  },
  {
    id: 3,
    title: "Sharwarma Plus+",
    image: sharwarma,
    rating: 4.7,
    deliveryFee: 200,
    deliveryTime: "20 min",
    discount: 40,
  },
  {
    id: 4,
    title: "Sharwarma Plus+",
    image: sharwarma,
    rating: 4.7,
    deliveryFee: 0,
    deliveryTime: "20 min",
    discount: 40,
  },
  {
    id: 5,
    title: "Sharwarma Plus+",
    image: sharwarma,
    rating: 4.7,
    deliveryFee: 200,
    deliveryTime: "20 min",
    discount: 40,
  },
];

export let featured = [
  {
    id: 1,
    title: "Sharwarma Plus+",
    image: sharwarma,
    rating: 4.7,
    deliveryFee: 200,
    deliveryTime: "20 min",
    discount: 40,
  },
  {
    id: 2,
    title: "Sharwarma Plus+",
    image: sharwarma,
    rating: 4.7,
    deliveryFee: 0,
    deliveryTime: "20 min",
    discount: 40,
  },
  {
    id: 3,
    title: "Sharwarma Plus+",
    image: sharwarma,
    rating: 4.7,
    deliveryFee: 200,
    deliveryTime: "20 min",
    discount: 40,
  },
  {
    id: 4,
    title: "Sharwarma Plus+",
    image: sharwarma,
    rating: 4.7,
    deliveryFee: 0,
    deliveryTime: "20 min",
    discount: 40,
  },
  {
    id: 6,
    title: "Sharwarma Plus+",
    image: sharwarma,
    rating: 4.7,
    deliveryFee: 200,
    deliveryTime: "20 min",
    discount: 40,
  },
];

export let restaurants = [
  {
    id: 1,
    title: "Sharwarma Plus+",
    image: sharwarma,
    rating: 4.7,
    deliveryFee: 200,
    deliveryTime: "20 min",
    discount: 40,
  },
  {
    id: 2,
    title: "Sharwarma Plus+",
    image: sharwarma,
    rating: 4.7,
    deliveryFee: 0,
    deliveryTime: "20 min",
    discount: 40,
  },
  {
    id: 3,
    title: "Sharwarma Plus+",
    image: sharwarma,
    rating: 4.7,
    deliveryFee: 200,
    deliveryTime: "20 min",
    discount: 40,
  },
  {
    id: 4,
    title: "Sharwarma Plus+",
    image: sharwarma,
    rating: 4.7,
    deliveryFee: 0,
    deliveryTime: "20 min",
    discount: 40,
  },
  {
    id: 5,
    title: "Sharwarma Plus+",
    image: sharwarma,
    rating: 4.7,
    deliveryFee: 200,
    deliveryTime: "20 min",
    discount: 40,
  },
  {
    id: 6,
    title: "Sharwarma Plus+",
    image: sharwarma,
    rating: 4.7,
    deliveryFee: 200,
    deliveryTime: "20 min",
    discount: 40,
  },
];

export const categories = [
  {
    id: "Restaurants",
    name: "Restaurants",
    icon: restaurant,
  },
  {
    id: "Groceries",
    name: "Groceries & More",
    icon: groceries,
  },
  {
    id: "Markets",
    name: "Markets",
    icon: food,

  },
];

export const Restaurants:Record<string, Product[]> = {
  1: [
    {
      id: "1",
      name: "Pepperoni Pizza",
      description:
        "Hot & fresh pizza adorned with pepperoni on tomato marinara sauce and mozzarella cheese",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "2",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "3",
      name: "Chicken Shawarma",
      description: "Juicy marinated chicken wrapped in soft pita bread...",
      imageUrl: pizza.src,
      price: "5253",
      categoryId: "shawarma",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.6,
      bayesianRating: 4.5,
    },
    {
      id: "4",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "5",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "6",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "7",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
  ],
  2: [
    {
      id: "1",
      name: "Pepperoni Pizza",
      description:
        "Hot & fresh pizza adorned with pepperoni on tomato marinara sauce and mozzarella cheese",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "2",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "3",
      name: "Chicken Shawarma",
      description: "Juicy marinated chicken wrapped in soft pita bread...",
      imageUrl: pizza.src,
      price: "5253",
      categoryId: "shawarma",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.6,
      bayesianRating: 4.5,
    },
    {
      id: "4",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "5",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "6",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "7",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
  ],
  3: [
    {
      id: "1",
      name: "Pepperoni Pizza",
      description:
        "Hot & fresh pizza adorned with pepperoni on tomato marinara sauce and mozzarella cheese",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "2",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "3",
      name: "Chicken Shawarma",
      description: "Juicy marinated chicken wrapped in soft pita bread...",
      imageUrl: pizza.src,
      price: "5253",
      categoryId: "shawarma",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.6,
      bayesianRating: 4.5,
    },
    {
      id: "4",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "5",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "6",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "7",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
  ],
  4: [
    {
      id: "1",
      name: "Pepperoni Pizza",
      description:
        "Hot & fresh pizza adorned with pepperoni on tomato marinara sauce and mozzarella cheese",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "2",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "3",
      name: "Chicken Shawarma",
      description: "Juicy marinated chicken wrapped in soft pita bread...",
      imageUrl: pizza.src,
      price: "5253",
      categoryId: "shawarma",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.6,
      bayesianRating: 4.5,
    },
    {
      id: "4",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "5",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "6",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
    {
      id: "7",
      name: "Pepperoni Pizza",
      description: "Hot & fresh pizza adorned with pepperoni on tomato...",
      imageUrl: pizza.src,
      price: "9650",
      categoryId: "pizza",
      isMenuSet: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      vendor: {
        id: "v1",
        businessName: "Shawarma Plus",
        createdAt: new Date().toISOString(),
        businessCategory: "Restaurant",
        businessAddress: "123 Food St",
        isPreorder: false,
        golive: true,
        totalOrders: 2342,
        reviews: [],
      },
      simpleRating: 4.5,
      bayesianRating: 4.4,
    },
  ],
};

export const hotPicks = [
    {
      name: "Food Cafe",
      image: foodCafe.src,
      link: "",
    },
    {
      name: "Suya Bistro",
      image: suyaBistro.src,
      link: "",
    },
    {
      name: "Divine Spot",
      image: divineSpot.src,
      link: "",
    },
    {
      name: "Choppers",
      image: choppers.src,
      link: "",
    },
    {
      name: "Pappies Maestro",
      image: pappiesMaestro.src,
      link: "",
    },
    {
      name: "Pizza Hut",
      image: pizzaHut.src,
      link: "",
    },
  ];
